name: Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deploy-to-huggingface:
    runs-on: ubuntu-latest
    env:
      HF: ${{ secrets.HF }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install huggingface CLI
        run: |
          pip install -U "huggingface_hub[cli]"

      - name: Login to Hugging Face Hub
        run: |
          huggingface-cli login --token $HF --add-to-git-credential

      - name: Push App folder to Hugging Face
        run: |
          huggingface-cli upload Sokol77/Projekt_SUML ./app /app --repo-type=space --commit-message="Sync App files"
          huggingface-cli upload Sokol77/Projekt_SUML ./Results /results --repo-type=space --commit-message="Sync results"
          huggingface-cli upload Sokol77/Projekt_SUML ./model /model --repo-type=space --commit-message="Sync Model"
          huggingface-cli upload Sokol77/Projekt_SUML ./data /data --repo-type=space --commit-message="Sync data"
  
  deploy: hf-login push-hub
